SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

CREATE TABLE IF NOT EXISTS `aufgaben` (
	`id`	int(11) NOT NULL,
	`aufgabe`	text NOT NULL,
	`loesung`	text NOT NULL,
	`schwierigkeit`	int(11) DEFAULT NULL,
	`hinweis`	varchar(250) NOT NULL,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `GEO_BERG` (
	`id`	int(11) NOT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`LT_ID`	varchar(4) DEFAULT NULL,
	`B_NAME`	varchar(20) DEFAULT NULL,
	CONSTRAINT `geo_berg_ibfk_1` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	CONSTRAINT `geo_berg_ibfk_2` FOREIGN KEY(`B_NAME`) REFERENCES `BERG`(`B_NAME`),
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `GEO_FLUSS` (
	`id`	int(11) NOT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`LT_ID`	varchar(50) DEFAULT NULL,
	`F_NAME`	varchar(20) DEFAULT NULL,
	CONSTRAINT `geo_fluss_ibfk_1` FOREIGN KEY(`F_NAME`) REFERENCES `FLUSS`(`F_NAME`),
	CONSTRAINT `geo_fluss_ibfk_2` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `GEO_MEER` (
	`id`	int(11) NOT NULL,
	`LT_ID`	varchar(4) DEFAULT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`M_NAME`	varchar(25) DEFAULT NULL,
	CONSTRAINT `geo_meer_ibfk_1` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	CONSTRAINT `geo_meer_ibfk_2` FOREIGN KEY(`M_NAME`) REFERENCES `MEER`(`M_NAME`),
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `GEO_SEE` (
	`id`	int(11) NOT NULL,
	`LT_ID`	varchar(4) DEFAULT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`S_NAME`	varchar(25) DEFAULT NULL,
	CONSTRAINT `geo_see_ibfk_1` FOREIGN KEY(`S_NAME`) REFERENCES `SEE`(`S_NAME`),
	CONSTRAINT `geo_see_ibfk_2` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `KONTINENT` (
	`K_NAME`	varchar(10) NOT NULL DEFAULT '',
	`FLAECHE`	double(16, 4) DEFAULT NULL,
	PRIMARY KEY(`K_NAME`)
);
CREATE TABLE IF NOT EXISTS `LANDTEIL` (
	`id`	int(11) NOT NULL,
	`LT_ID`	varchar(4) DEFAULT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`LT_NAME`	varchar(50) NOT NULL DEFAULT '',
	`EINWOHNER`	double(16, 4) DEFAULT NULL,
	`LAGE`	char(2) DEFAULT NULL,
	`HAUPTSTADT`	varchar(25) DEFAULT NULL,
	CONSTRAINT `landteil_ibfk_1` FOREIGN KEY(`L_ID`) REFERENCES `LAND`(`L_ID`),
	PRIMARY KEY(`L_ID`, `LT_ID`, `id`)
);
CREATE TABLE IF NOT EXISTS `LIEGT_AN` (
	`id`	int(11) NOT NULL,
	`ST_NAME`	varchar(25) DEFAULT NULL,
	`LT_ID`	varchar(4) DEFAULT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`F_NAME`	varchar(20) DEFAULT NULL,
	`S_NAME`	varchar(25) DEFAULT NULL,
	`M_NAME`	varchar(25) DEFAULT NULL,
	CONSTRAINT `liegt_an_ibfk_1` FOREIGN KEY(`S_NAME`) REFERENCES `SEE`(`S_NAME`),
	CONSTRAINT `liegt_an_ibfk_2` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	CONSTRAINT `liegt_an_ibfk_3` FOREIGN KEY(`L_ID`) REFERENCES `LAND`(`L_ID`),
	CONSTRAINT `liegt_an_ibfk_4` FOREIGN KEY(`M_NAME`) REFERENCES `MEER`(`M_NAME`),
	CONSTRAINT `liegt_an_ibfk_5` FOREIGN KEY(`F_NAME`) REFERENCES `FLUSS`(`F_NAME`),
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `ORGANISATION` (
	`id`	int(11) NOT NULL,
	`O_NAME`	varchar(70) DEFAULT NULL,
	`ABKUERZUNG`	varchar(20) DEFAULT NULL,
	PRIMARY KEY(`ABKUERZUNG`,`id`)
);
CREATE TABLE IF NOT EXISTS `UMFASST` (
	`id`	int(11) NOT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`K_NAME`	varchar(10) DEFAULT NULL,
	`PROZENT`	double(16, 4) DEFAULT NULL,
	CONSTRAINT `umfasst_ibfk_1` FOREIGN KEY(`K_NAME`) REFERENCES `KONTINENT`(`K_NAME`),
	CONSTRAINT `umfasst_ibfk_2` FOREIGN KEY(`L_ID`) REFERENCES `LAND`(`L_ID`),
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `WUESTE` (
	`id`	int(11) NOT NULL,
	`W_NAME`	varchar(25) DEFAULT NULL,
	`FLAECHE`	double(16, 4) DEFAULT NULL,
	`WUESTENART`	varchar(17) DEFAULT NULL,
	PRIMARY KEY(`W_NAME`,`id`)
);
CREATE TABLE IF NOT EXISTS `IST_BENACHBART_ZU` (
	`id`	int(11) NOT NULL,
	`LAND1`	varchar(4) DEFAULT NULL,
	`LAND2`	varchar(4) DEFAULT NULL,
	CONSTRAINT `ist_benachbart_zu_ibfk_1` FOREIGN KEY(`LAND2`) REFERENCES `LAND`(`L_ID`),
	CONSTRAINT `ist_benachbart_zu_ibfk_2` FOREIGN KEY(`LAND1`) REFERENCES `LAND`(`L_ID`),
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `FLUSS` (
	`F_NAME`	varchar(20) NOT NULL DEFAULT '',
	`FLUSS`	varchar(20) DEFAULT NULL,
	`SEE`	varchar(25) DEFAULT NULL,
	`MEER`	varchar(25) DEFAULT NULL,
	`LAENGE`	int(11) DEFAULT NULL,
	`LAENGEU`	double(16, 4) DEFAULT NULL,
	`BREITEU`	double(16, 4) DEFAULT NULL,
	`LAENGEM`	double(16, 4) DEFAULT NULL,
	`BREITEM`	double(16, 4) DEFAULT NULL,
	CONSTRAINT `fluss_ibfk_1` FOREIGN KEY(`SEE`) REFERENCES `SEE`(`S_NAME`),
	CONSTRAINT `fluss_ibfk_2` FOREIGN KEY(`MEER`) REFERENCES `MEER`(`M_NAME`),
	PRIMARY KEY(`F_NAME`)
);
CREATE TABLE IF NOT EXISTS `EBENE` (
	`E_NAME`	varchar(25) NOT NULL DEFAULT '',
	`HOEHE`	double(16, 4) DEFAULT NULL,
	`FLAECHE`	double(16, 4) DEFAULT NULL,
	PRIMARY KEY(`E_NAME`)
);
CREATE TABLE IF NOT EXISTS `BERG` (
	`B_NAME`	varchar(20) NOT NULL DEFAULT '',
	`GEBIRGE`	varchar(25) DEFAULT NULL,
	`HOEHE`	double(16, 4) DEFAULT NULL,
	`JAHR`	int(11) DEFAULT NULL,
	`LAENGE`	double(16, 4) DEFAULT NULL,
	`BREITE`	double(16, 4) DEFAULT NULL,
	PRIMARY KEY(`B_NAME`)
);
CREATE TABLE IF NOT EXISTS `GEHT_UEBER_IN` (
	`MEER1`	varchar(25) DEFAULT NULL,
	`MEER2`	varchar(25) DEFAULT NULL,
	CONSTRAINT `geht_ueber_in_ibfk_1` FOREIGN KEY(`MEER1`) REFERENCES `MEER`(`M_NAME`),
	CONSTRAINT `geht_ueber_in_ibfk_2` FOREIGN KEY(`MEER2`) REFERENCES `MEER`(`M_NAME`),
	PRIMARY KEY(`MEER1`,`MEER2`)
);
CREATE TABLE IF NOT EXISTS `GEO_EBENE` (
	`LT_ID`	varchar(4) DEFAULT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`E_NAME`	varchar(25) DEFAULT NULL,
	CONSTRAINT `geo_ebene_ibfk_1` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	CONSTRAINT `geo_ebene_ibfk_2` FOREIGN KEY(`E_NAME`) REFERENCES `EBENE`(`E_NAME`),
	PRIMARY KEY(`LT_ID`,`L_ID`,`E_NAME`)
);
CREATE TABLE IF NOT EXISTS `GEO_INSEL` (
	`LT_ID`	varchar(4) DEFAULT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`I_NAME`	varchar(25) DEFAULT NULL,
	CONSTRAINT `geo_insel_ibfk_1` FOREIGN KEY(`I_NAME`) REFERENCES `INSEL`(`I_NAME`),
	CONSTRAINT `geo_insel_ibfk_2` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	PRIMARY KEY(`LT_ID`,`L_ID`,`I_NAME`)
);
CREATE TABLE IF NOT EXISTS `GEO_WUESTE` (
	`LT_ID`	varchar(4) DEFAULT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`W_NAME`	varchar(25) DEFAULT NULL,
	CONSTRAINT `geo_wueste_ibfk_1` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	CONSTRAINT `geo_wueste_ibfk_2` FOREIGN KEY(`W_NAME`) REFERENCES `WUESTE`(`W_NAME`),
	PRIMARY KEY(`LT_ID`,`L_ID`,`W_NAME`)
);
CREATE TABLE IF NOT EXISTS `HAT_SITZ_IN` (
	`ST_NAME`	varchar(25) DEFAULT NULL,
	`LT_ID`	varchar(4) DEFAULT NULL,
	`L_ID`	varchar(4) DEFAULT NULL,
	`ABKUERZUNG`	varchar(20) DEFAULT NULL,
	CONSTRAINT `hat_sitz_in_ibfk_1` FOREIGN KEY(`L_ID`,`LT_ID`,`ST_NAME`) REFERENCES `STADT`(`L_ID`,`LT_ID`,`ST_NAME`),
	CONSTRAINT `hat_sitz_in_ibfk_2` FOREIGN KEY(`ABKUERZUNG`) REFERENCES `ORGANISATION`(`ABKUERZUNG`),
	PRIMARY KEY(`ABKUERZUNG`)
);
CREATE TABLE IF NOT EXISTS `INSEL` (
	`I_NAME`	varchar(25) NOT NULL DEFAULT '',
	`INSELGRUPPE`	varchar(25) DEFAULT NULL,
	`FLAECHE`	double(16, 4) DEFAULT NULL,
	`LAENGE`	double(16, 4) DEFAULT NULL,
	`BREITE`	double(16, 4) DEFAULT NULL,
	PRIMARY KEY(`I_NAME`)
);
CREATE TABLE IF NOT EXISTS `IST_MITGLIED_VON` (
	`L_ID`	varchar(4) DEFAULT NULL,
	`ABKUERZUNG`	varchar(20) DEFAULT NULL,
	`ART`	varchar(25) DEFAULT NULL,
	CONSTRAINT `ist_mitglied_von_ibfk_1` FOREIGN KEY(`L_ID`) REFERENCES `LAND`(`L_ID`),
	CONSTRAINT `ist_mitglied_von_ibfk_2` FOREIGN KEY(`ABKUERZUNG`) REFERENCES `ORGANISATION`(`ABKUERZUNG`),
	PRIMARY KEY(`ABKUERZUNG`,`L_ID`)
);
CREATE TABLE IF NOT EXISTS `LAND` (
	`L_ID`	varchar(4) NOT NULL DEFAULT '',
	`L_NAME`	varchar(50) DEFAULT NULL,
	`EINWOHNER`	double(16, 4) DEFAULT NULL,
	`FLAECHE`	double(16, 4) DEFAULT NULL,
	`HAUPTSTADT`	varchar(25) DEFAULT NULL,
	`LT_ID`	varchar(4) DEFAULT NULL,
	CONSTRAINT `land_ibfk_1` FOREIGN KEY(`L_ID`,`LT_ID`,`HAUPTSTADT`) REFERENCES `STADT`(`L_ID`,`LT_ID`,`ST_NAME`),
	CONSTRAINT `land_ibfk_2` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	PRIMARY KEY(`L_ID`)
);
CREATE TABLE IF NOT EXISTS `MEER` (
	`M_NAME`	varchar(25) NOT NULL DEFAULT '',
	`TIEFE`	double(16, 4) DEFAULT NULL,
	PRIMARY KEY(`M_NAME`)
);
CREATE TABLE IF NOT EXISTS `SEE` (
	`S_NAME`	varchar(25) DEFAULT NULL,
	`TIEFE`	double(16, 4) DEFAULT NULL,
	`FLAECHE`	double(16, 4) DEFAULT NULL,
	PRIMARY KEY(`S_NAME`)
);
CREATE TABLE IF NOT EXISTS `STADT` (
	`ST_NAME`	varchar(25) NOT NULL DEFAULT '',
	`L_ID`	varchar(4) DEFAULT NULL,
	`LT_ID`	varchar(4) DEFAULT NULL,
	`EINWOHNER`	int(11) DEFAULT NULL,
	`BREITE`	double(16, 4) DEFAULT NULL,
	`LAENGE`	double(16, 4) DEFAULT NULL,
	CONSTRAINT `stadt_ibfk_1` FOREIGN KEY(`L_ID`) REFERENCES `LAND`(`L_ID`),
	CONSTRAINT `stadt_ibfk_2` FOREIGN KEY(`L_ID`,`LT_ID`) REFERENCES `LANDTEIL`(`L_ID`,`LT_ID`),
	PRIMARY KEY(`L_ID`,`LT_ID`,`ST_NAME`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_k_name` ON `KONTINENT` (
	`K_NAME`
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_f_name` ON `FLUSS` (
	`F_NAME`
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_e_name` ON `EBENE` (
	`E_NAME`
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_b_name` ON `BERG` (
	`B_NAME`
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_i_name` ON `INSEL` (
	`I_NAME`
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_l_id2` ON `LAND` (
	`L_ID`
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_l_id3` ON `LAND` (
	`L_ID`
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_m_name` ON `MEER` (
	`M_NAME`
);
CREATE UNIQUE INDEX IF NOT EXISTS `ix_st_name` ON `STADT` (
	`ST_NAME`
);
COMMIT;
